# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/functions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/functions.proto\x12\x17rivoli.protos.functions\"\x88\x01\n\x10\x46unctionResource\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tpartnerId\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x63redentials\x18\x05 \x01(\t\x12\x10\n\x08hostname\x18\x06 \x01(\t\x12\x10\n\x08qpmLimit\x18\x07 \x01(\r\"\x98\x06\n\x08\x46unction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\x12\x12\n\ndeprecated\x18\x0e \x01(\x08\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12<\n\x04type\x18\x05 \x01(\x0e\x32..rivoli.protos.functions.Function.FunctionType\x12\x0e\n\x06global\x18\x06 \x01(\x08\x12\x0e\n\x06system\x18\x07 \x01(\x08\x12\x11\n\tpartnerId\x18\x08 \x03(\t\x12\x18\n\x0epythonFunction\x18\t \x01(\tH\x00\x12\x14\n\njsFunction\x18\n \x01(\tH\x00\x12\x10\n\x06jsCode\x18\x0b \x01(\tH\x00\x12\x11\n\x07sqlCode\x18\x0c \x01(\tH\x00\x12?\n\nparameters\x18\r \x03(\x0b\x32+.rivoli.protos.functions.Function.Parameter\x1a\r\n\x0b\x41piEndpoint\x1a\x86\x01\n\tParameter\x12\x14\n\x0cvariableName\x18\x01 \x01(\t\x12\x38\n\x04type\x18\x04 \x01(\x0e\x32*.rivoli.protos.functions.Function.DataType\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x65\x66\x61ultValue\x18\x03 \x01(\t\"\xb0\x01\n\x0c\x46unctionType\x12\x19\n\x15\x46UNCTION_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10\x46IELD_VALIDATION\x10\x01\x12\x15\n\x11RECORD_VALIDATION\x10\x02\x12\x11\n\rRECORD_UPLOAD\x10\x03\x12\x13\n\x0fRECORD_ROLLBACK\x10\x04\x12\x1c\n\x18RECORD_DUPLICATION_CHECK\x10\x06\x12\x12\n\x0e\x46IELD_RENDERER\x10\x07\"R\n\x08\x44\x61taType\x12\x15\n\x11\x44\x41TA_TYPE_UNKNOWN\x10\x00\x12\x0b\n\x07INTEGER\x10\x01\x12\t\n\x05\x46LOAT\x10\x02\x12\n\n\x06STRING\x10\x03\x12\x0b\n\x07\x42OOLEAN\x10\x04\x42\x13\n\x11\x66unctionStatementb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.functions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNCTIONRESOURCE._serialized_start=52
  _FUNCTIONRESOURCE._serialized_end=188
  _FUNCTION._serialized_start=191
  _FUNCTION._serialized_end=983
  _FUNCTION_APIENDPOINT._serialized_start=549
  _FUNCTION_APIENDPOINT._serialized_end=562
  _FUNCTION_PARAMETER._serialized_start=565
  _FUNCTION_PARAMETER._serialized_end=699
  _FUNCTION_FUNCTIONTYPE._serialized_start=702
  _FUNCTION_FUNCTIONTYPE._serialized_end=878
  _FUNCTION_DATATYPE._serialized_start=880
  _FUNCTION_DATATYPE._serialized_end=962
# @@protoc_insertion_point(module_scope)
